cursor #ddc7a1
cursor_text_color #d4be98

foreground            #ddc7a1
background            #1d2021
selection_foreground  #141617
selection_background  #e78a4e
url_color             #7daea3

color0   #141617
color1   #c87e5a
color2   #57ae5c
color3   #d9cf61
color4   #6da598
color5   #265047
color6   #7daea3
color7   #abb6b4
color8   #727b79
color9   #eab092
color10  #87d08c
color11  #fff7a5
color12  #91bfb5
color13  #b5e2d8
color14  #d4f3ec
color15  #f5fcfa
