# add theme
# include gruvbox_dark_hard.conf

# font settings
# font_family         JetBrainsMonoNL NFM
# bold_font           auto
# italic_font         auto
# bold_italic_font    auto

font_size 18.0

# url style
url_style dashed

# mouse actions
select_by_word_characters @-./_~?&=%+#

# window settings
hide_window_decorations yes
window_padding_width 0
window_margin_width 10

# tiling
enabled_layouts stack

# background
background_opacity 1
background_blur 64

# cursor
cursor_shape block

# shell integration
# no-cursor means the shell won't influence the cursor shape
shell_integration no-cursor

# turn off the annoying bell sound
enable_audio_bell no

# give apps (eg: neovim) control of kitty
allow_remote_control yes
listen_on unix:/tmp/kitty

# tab bar style
tab_bar_align center
tab_fade 1 1 1 1
active_tab_font_style bold
tab_title_template " {index}: {title} "
tab_bar_style separator
tab_separator ""
tab_bar_margin_width 0.0
tab_bar_margin_height 2.0 2.0

# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
# font_family      family='JetBrainsMonoNL Nerd Font Mono' postscript_name=JetBrainsMonoNLNFM-Regular
font_family      FiraMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
