# add theme
# include gruvbox_dark_hard.conf

# font settings
font_family         Lilex Nerd Font Mono
bold_font           auto
italic_font         auto
bold_italic_font    auto

font_size 18.0

# url style
url_style dashed

# mouse actions
select_by_word_characters @-./_~?&=%+#

# window settings
hide_window_decorations yes
window_padding_width 10

# background
background_opacity 0.95

# cursor
cursor_shape block

# shell integration
# no-cursor means the shell won't influence the cursor shape
shell_integration no-cursor

# turn off the annoying bell sound
enable_audio_bell no

# BEGIN_KITTY_THEME
# kanagawabones
include current-theme.conf
# END_KITTY_THEME
